#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-execjs
Version  : 2.7.0
Release  : 7
URL      : https://rubygems.org/downloads/execjs-2.7.0.gem
Source0  : https://rubygems.org/downloads/execjs-2.7.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
ExecJS
======
ExecJS lets you run JavaScript code from Ruby. It automatically picks
the best runtime available to evaluate your JavaScript program, then
returns the result to you as a Ruby object.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n execjs-2.7.0
gem spec %{SOURCE0} -l --ruby > rubygem-execjs.gemspec

%build
gem build rubygem-execjs.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
execjs-2.7.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/execjs-2.7.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/disabled_runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/duktape_runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/mini_racer_runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/module.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/ruby_rhino_runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/support/jsc_runner.js
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/support/jscript_runner.js
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/support/json2.js
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/support/node_runner.js
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/support/spidermonkey_runner.js
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/support/v8_runner.js
/usr/lib64/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/execjs-2.7.0.gemspec
